/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataView: typeof import('primevue/dataview')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Slider: typeof import('primevue/slider')['default']
    Tag: typeof import('primevue/tag')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
